import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
// import Footer from "@/components/common/Footer";

export const metadata: Metadata = {
  title: "Bryan Aaron Santiago",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="">
        <svg className="pointer-events-none absolute cursor-none">
          <filter id="grainy">
            <feTurbulence 
              type="turbulence" 
              baseFrequency="0.8" 
              // numOctaves="6" 
              // stitchTiles="stitch"
            >
            </feTurbulence>
            <feColorMatrix type="saturate" values="0"></feColorMatrix>
          </filter>
        </svg>
        <Navbar />
          {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
