import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
// import Footer from "@/components/common/Footer";

export const metadata: Metadata = {
  title: "Bryan Aaron Santiago",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="">
        <Navbar />
          {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
